# Generated by Django 3.1.7 on 2022-05-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220522_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='vk',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='work_experience',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.TextField(default=''),
        ),
    ]
