# Generated by Django 3.1.7 on 2022-05-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220522_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='main.Technology'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='vk',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_experience',
            field=models.TextField(blank=True, default=''),
        ),
    ]
