# Generated by Django 2.2.4 on 2022-05-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220530_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('0', 'В процессе'), ('1', 'На проверке'), ('2', 'Возвращено'), ('3', 'Сделано')], default=('0', 'В процессе'), max_length=1),
        ),
    ]
