# Generated by Django 2.2.4 on 2022-05-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220530_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('0', 'В процессе'), ('1', 'На проверке'), ('2', 'Возвращено'), ('3', 'Сделано')], default='0', max_length=1),
        ),
    ]
